"""all

Revision ID: 27ad6c8651f3
Revises: 8b60877c134c
Create Date: 2023-04-18 22:51:47.521133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ad6c8651f3'
down_revision = '8b60877c134c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoot_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locations', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('num_photos_requested', sa.Integer(), nullable=True),
    sa.Column('model_release', sa.String(), nullable=True),
    sa.Column('branding', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_information', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('payment_information')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    op.drop_table('shoot_information')
    # ### end Alembic commands ###
