"""updated Shoot table

Revision ID: 77ed3f56181f
Revises: 9b430b01558d
Create Date: 2023-04-20 22:30:46.120676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ed3f56181f'
down_revision = '9b430b01558d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoot_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lens_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_lens_id', 'lens', ['lens_id'], ['id'])
        batch_op.create_foreign_key('fk_camera_id', 'camera', ['camera_id'], ['id'])
        batch_op.drop_column('equipment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoot_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lens_id')
        batch_op.drop_column('camera_id')

    # ### end Alembic commands ###
